### ISSUE TITLE
content.xml not found

### ISSUE THREAD

**Issue by jalena** [ecd-plugin/ecd#86] opened 2022-06-27 01:57 UTC
https://ecd-plugin.github.io/update/content.xml not found

**Comment by jpstotz** [comment] 2022-06-27 07:28
@jalena Which Eclipse version do you use?

**Comment by RobertZenz** [comment] 2022-06-28 15:28
Should be a duplicate of #11, something wrong with your (Eclipse) proxy configuration.

**Closed** 2023-05-01 16:05 UTC
