### ISSUE TITLE
Unknown host https://ecd-plugin.github.io/update/content.xml

### ISSUE THREAD

**Issue by Tohnmeister** [ecd-plugin/ecd#30] opened 2017-12-01 08:11 UTC
When I try to install the plugin using the install shortcut, I get the following error:

![image](https://user-images.githubusercontent.com/1702409/33473623-7c02db64-d677-11e7-9030-436fd92ff715.png)

**Comment by RobertZenz** [comment] 2017-12-03 18:22
That is most likely a duplicate of #11, please check your proxy configuration.

**Comment by pierreonthenet** [comment] 2018-02-02 09:46
I have exactly the same problem with a fresh install of Eclipse Mars 2 64bit (Version: Mars.2 Release (4.5.2) Build id: 20160218-0600).
I don't have access to https://ecd-plugin.github.io/update/content.xml as well, and this is NOT a proxy problem.
Does anyone can access this ?

**Comment by pbi-qfs** [comment] 2018-02-02 10:02
Current versions of Eclipse do not need this file on the update site, but report rather a general network error with the cited message.

I provided an extracted version of content.jar now so the file should not reported missing anymore - does this help you with your Eclipse installation?

**Comment by pbi-qfs** [comment] 2018-06-13 16:18
Closing this issue as it seems not be reproducible. If it is, please reopen the issue.

**Closed by pbi-qfs** 2018-06-13 16:18 UTC
Labels: question
