### ISSUE TITLE
class Decompiler 3.0.0 can not be decompiled, can you help me?

### ISSUE THREAD

**Issue by qifei0708** [ecd-plugin/ecd#28] opened 2017-11-18 11:49 UTC
I use ide is STS, when I can not decompile after installing class Decompiler 3.0.0,I've tried all the configurations inside this.

![decompiler](https://user-images.githubusercontent.com/27794583/32979968-76b1787e-cc99-11e7-95ac-6eca6b5103bb.png)
![eclipse](https://user-images.githubusercontent.com/27794583/32979972-7d58a80a-cc99-11e7-8fcb-1ac7db9c703d.png)
![todo](https://user-images.githubusercontent.com/27794583/32979975-85d9b73a-cc99-11e7-820a-ad7c428c9c0e.png)

**Comment by RobertZenz** [comment] 2017-11-19 19:26
Mh, odd, no idea to be honest.

That you use STS shouldn't make a difference, except if STS is doing something odd which it shouldn't be doing. I'll see if I can reproduce this.

**Comment by tbraas** [comment] 2017-11-21 04:57
I'm having the same issue. It would appear that the internal JDT API has changed and this plugin needs to be updated to work. Specifically the SourceMapper class has changed. If you open up the plugin project in Eclipse Oxygen 4.7.1a you won't be able to build it due to the changes. At least I wasn't able to build it.

I don't have the Oxygen Java 9 Beta plugin installed.

**Comment by RobertZenz** [comment] 2017-11-21 08:16
@tbraas That I do know, that is #12 and has been fixed in the 3.0 release.

**Comment by qifei0708** [comment] 2017-11-22 02:14
@RobertZenz 
Thank you very much!
My sts is the latest download, I did not make any changes to it.
But to find the need to decompile the class file -> right -> class to open the way, which can choose any mode to achieve the anti-compiled classs

**Comment by RobertZenz** [comment] 2017-11-22 08:48
@qifei0708 Did I understand you right that you can view the decompiled source when you open the open the class file with the correct viewer? If that is the case, that I can look into.

**Comment by qifei0708** [comment] 2017-11-22 08:55
@RobertZenz 
My English is really bad, I'm sorry I did not make it clear, I would like to say: STS can not automatically decompile, but you can manually decompile.
![1](https://user-images.githubusercontent.com/27794583/33118115-bf5043c6-cfa5-11e7-913b-2bea5a8aabe7.png)
![2](https://user-images.githubusercontent.com/27794583/33118123-c9644452-cfa5-11e7-85f4-4f7eb933b362.png)
![3](https://user-images.githubusercontent.com/27794583/33118126-cc7bd4a2-cfa5-11e7-9c7f-ef9b02d5f4c9.png)

**Comment by RobertZenz** [comment] 2017-11-22 09:34
I see, seems like the automatic binding of the correct editor has failed.

Could you please check the file associations in the preferences (`Window -> Preferences`):

    General -> Editors -> File Associations

Make sure that the "Class Decompiler Viewer" is set as the default.

**Comment by qifei0708** [comment] 2017-12-12 01:58
@RobertZenz I checked, my configuration is no problem.
But now it works, I really feel you!
![1](https://user-images.githubusercontent.com/27794583/33863483-ed36ddc2-df22-11e7-8116-c3d56ad1cba4.png)
![2](https://user-images.githubusercontent.com/27794583/33863484-f03889b2-df22-11e7-9d28-567837ccd3b0.png)

**Closed** 2017-12-12 08:02 UTC
Labels: question
