### ISSUE TITLE
Notice: Jar Files

### ISSUE THREAD

**Issue by nickl-** [ecd-plugin/ecd#25] opened 2017-11-13 06:03 UTC
I am still completely where it comes to my actual needs but I think I managed to find out how to implement the jar file browsing. This serves as notice that I will be working on making jar files or java archives in general viewable, for now.

From what I can tell we need to provide a `org.eclipse.ui.navigator.navigatorContent` extension which means we must implement `org.eclipse.jface.viewers.ITreeContentProvider` to list the content of these archives. 

I am going to try and convince eclipse that it is just like any other folder by using the `jar://` url schema as file path. Well that's the plan anyway lets see how it goes.

**Comment by pbi-qfs** [comment] 2018-06-13 16:23
Duplicate of #4?

**Closed by pbi-qfs** 2018-06-13 16:23 UTC
Labels: enhancement
