### ISSUE TITLE
Inner and anonymous classes not present in FernFlower decompilation

### ISSUE THREAD

**Issue by TheKodeToad** [ecd-plugin/ecd#88] opened 2022-07-22 13:49 UTC
Source file:
```java

public class Main {

    Status status = Status.OK;

    void run() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                status = Status.ABORTED;
            }
        }).start();
    }

    enum Status {
        OK,
        ABORTED
    }

}

```

Decompilation (ECD FernFlower):
```java
import Main.1;
import Main.Status;

public class Main {
	Status status;

	public Main() {
		this.status = Status.OK;
	}

	void run() {
      (new Thread(new 1(this))).start();
   }
}

/*
	DECOMPILATION REPORT

	Decompiled from: /home/me/eclipse-workspace/Example/bin/Main.class
	Total time: 7 ms
	
	Decompiled with FernFlower.
*/
```

Decompilation (CLI FernFlower):
```java
public class Main {
   Main.Status status;

   public Main() {
      this.status = Main.Status.OK;
   }

   void run() {
      (new Thread(new Runnable() {
         public void run() {
            Main.this.status = Main.Status.ABORTED;
         }
      })).start();
   }

   static enum Status {
      OK,
      ABORTED;
   }
}

```

**Comment by jpstotz** [comment] 2022-07-22 16:52
@TheKodeToad Please provide a full description of your problem including an example of the decompiled class that you think is decompiled wrong. Note that ECD just uses FernFlower so unless it is a missing option set when using FernFlower the ECD issues tracker is the wrong place for your issue.

**Comment by TheKodeToad** [comment] 2022-07-22 17:22
It pretty much happens in all cases, which is why I felt a description wasn't necceccary. I can't provide the classes, since they are proprietary. I also know that this issue does not occur on FernFlower.

**Comment by jpstotz** [comment] 2022-07-25 17:07
Thanks, I was able to reproduce the problem. Even using the same FernFlower library included in ECD on command-line the output is OK, via ECD not.

The root cause seems to be that ECD filters the classes provided to FernFlower in an incorrect way.

**Comment by jpstotz** [comment] 2022-07-25 17:22
I fixed the problem, it fix will be included in the next release.

**Closed by jpstotz** 2022-07-25 17:22 UTC
