### ISSUE TITLE
ECD plugin installation on eclipse oxygen failed

### ISSUE THREAD

**Issue by cmeng-git** [ecd-plugin/ecd#15] opened 2017-10-11 00:28 UTC
I upgraded to Eclipse oxygen from a previously installed neon release; and using an existing working directory which contains old plugins. It includes an old not working plugin i.e. org.sf.feeling.decompiler.update. Eclipse oxygen is running on windows 7 64 bits with java 1.8 release 144.

There is no problem with the ECD installation. However the option "Window | Preferences | Jave | Decompiler" is missing / not shown; and jar decompilation is not working

Also the installed ECD did get listed in the About Installation Details as shown below. I also try to uninstalled and re-installed but problem remains.

Enhanced Class Decompiler (Core) 3.0.0.201709092115 org.sf.feeling.decompiler.feature.group ECD project contributors
Enhanced Class Decompiler CFR Extension (Optional) 3.0.0.201709092115 org.sf.feeling.decompiler.cfr.feature.group ECD project contributors
Enhanced Class Decompiler Jad Extension (Optional) 3.0.0.201709092115 org.sf.feeling.decompiler.jad.feature.group ECD project contributors
Enhanced Class Decompiler JD-Core Extension (Optional) 3.0.0.201709092115 org.sf.feeling.decompiler.jd.feature.group ECD project contributors
Enhanced Class Decompiler Procyon Extension (Optional) 3.0.0.201709092115 org.sf.feeling.decompiler.procyon.feature.group ECD project contributors
Enhanced Class Decompiler Source (Optional) 3.0.0.201709092115 org.sf.feeling.decompiler.source.feature.group ECD project contributors

I then tried to freshly reinstall eclipse oxyen (after removing old directory \Program Files\eclipse and ~/.p2). But still configure to use existing working directory. This time I can see the Java|Decompiler. However when I open a jar file in the project, it shows the jar content in binary decoded text without source decompiling. I try to set to other Default Class Decompiler other than the default FernFlower. None of the jar file can be opened. It seem to have popped up some error message briefly but too fast to read anything. 

However I see that for jar's that are on maven, it appears to be able to link the jar to the source. 

I then changed the working directory to a new empty directory, still there is no change in the problem. The ECD is just not working. 
Currently I am using an external installed JD_GUI tool for jar file decompile.

**Comment by cmeng-git** [comment] 2017-10-11 02:22
Problem found. Actually ECD cannot read the class file directly from a jar file; instead it needs to use an zipEditor to unzip before it can use to open the class file. On ubuntu I installed the ZipEditor to open the jar file then only the ECD can decompile and view the class source file.

On Windows 7, although I have installed the zipEditor, but just cannot associate the jar with the ZipEditor (cannot found the tool).

With earlier eclipse release and Jad plugin, the jar is expanded in the package explorer, I can then directly click on the class file to view the source instead of using a ZipEditor. Does anybody know how to setup eclipse the expand the jar in the package explorer?

**Comment by cmeng-git** [comment] 2017-10-11 02:39
on Windows 7, I have to start eclipse oxyen with administrator right, then I can get zipEditor installation to work.

**Comment by RobertZenz** [comment] 2017-10-11 07:05
> ...and using an existing working directory which contains old plugins.

Ey...ahrm, I'm not sure how to put this, but I don't believe we ever verified that that works...maybe we should have done that some point. Mea culpa. If in doubt remove the old plugin and install this one.

 > Actually ECD cannot read the class file directly from a jar file...
 > 
 > With earlier eclipse release and Jad plugin, the jar is expanded in the package explorer, I can then directly click on the class file to view the source instead of using a ZipEditor.

I never tried that, there is no problem when using the "Referenced Libraries" nodes in the package explorer or project explorer. As a matter of fact, what you describe sounds like the "Referenced Libraries" nodes, and it sounds like that you're trying to open the jar "as file" instead. Yeah, I don't think we ever had the idea to do it that way, because 99.99% of the time a jar you want to look at is on the classpath, and so in the "Referenced Libraries" node.

 > on Windows 7, I have to start eclipse oxyen with administrator right, then I can get zipEditor installation to work.

Uhm, yeah, you might want to tell the ZipEditor author.

**Comment by pbi-qfs** [comment] 2018-06-13 16:22
Seems to be a duplicate of #4

**Closed by pbi-qfs** 2018-06-13 16:22 UTC
Labels: question
